### ISSUE TITLE
Installation fails due to error

### ISSUE THREAD

**Issue by nickbe** [stasgar/Visual_Bugtracker#15]
Migrating: 2018_10_10_000000_create_users_table

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alt
  er table `users` add unique `users_name_unique`(`name`))

In Connection.php line 458:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by stasgar** [comment]
Hi. Could you provide more information on what MySQL engine you using? It seems like the broblem is there.

I will try to reproduce it on my environment later, i'm at work right now. But as a temporary fix please try to edit `AppServiceProvider.php` file and inside the boot method set a default string length:
```php
use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}
```

**Comment by stasgar** [comment]
I've figured out that it's a problem related to [Bouncer](https://github.com/JosephSilber/bouncer) (package i use for fluent abilities system). It requires mysql 5.7+ for these tables. They actually suggest the same fix i did in their documentation: https://github.com/JosephSilber/bouncer#im-trying-to-run-the-migration-but-im-getting-a-sql-error-that-the-specified-key-was-too-long-what-does-that-mean.

I think you should try to ask them about this specific problem, i have no power here but to require a newer version of mysql :disappointed: 

I will update README.md with 5.7 mysql requirements anyway...

**Comment by nickbe** [comment]
ok. Will try

**Comment by nickbe** [comment]
mySQL Error seems to be resolved. 
But again another one:

λ php artisan bugwall:init --storage                                                                                          
This command will ERASE these directories (if they exists) WITH ALL OF THE FILES and set up a default directory structure for 
you:                                                                                                                          
/board_images/* /project_images/* /user_avatars/*                                                                             
                                                                                                                              
 Do you wish to continue? (yes/no) [no]:                                                                                      
 > yes                                                                                                                        
                                                                                                                              
                                                                                                                              
In WrappedHttpHandler.php line 191:                                                                                           
                                                                                                                              
  Error executing "ListObjects" on "https://s3.region.amazonaws.com/BUCKET?prefix=board_images%2F&max-keys=1&encoding-type=   
  url"; AWS HTTP error: cURL error 6: Could not resolve host: s3.region.amazonaws.com (see http://curl.haxx.se/libcurl/c/li   
  bcurl-errors.html)                                                                                                          
                                                                                                                              
                                                                                                                              
In CurlFactory.php line 185:                                                                                                  
                                                                                                                              
  cURL error 6: Could not resolve host: s3.region.amazonaws.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by nickbe** [comment]
After that:

( ! )  Parse error: syntax error, unexpected '?' in  Visual_Bugtracker\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php  on line 500
--


1 | 0.0007 | 134096 | {main}(  ) | ...\index.php:0
2 | 0.0010 | 135384 | require( 'Visual_Bugtracker\bootstrap\autoload.php' ) | ...\index.php:22
3 | 0.0012 | 136648 | require( 'Visual_Bugtracker\vendor\autoload.php' ) | ...\autoload.php:17
4 | 0.0015 | 149176 | ComposerAutoloaderInit360520585137cf04e8cb931781c29448::getLoader(  ) | ...\autoload.php:7
5 | 0.0186 | 1762816 | composerRequire360520585137cf04e8cb931781c29448(  ) | ...\autoload_real.php:56

**Comment by stasgar** [comment]
> In WrappedHttpHandler.php line 191:
> 
> Error executing "ListObjects" on "https://s3.region.amazonaws.com/BUCKET?prefix=board_images%2F&max-keys=1&encoding-type=

Because you are trying to connect to dummy storage (these values in .env should be changed to your aws s3 container settings). I mentioned it in README.md, if you want to use W3 storage - you should create it on amazon aws website. I also have instruction for changing it to local storage, you should stick to it then.

> After that:
> 
> ## ( ! ) Parse error: syntax error, unexpected '?' in Visual_Bugtracker\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php on line 500

PHP 7 has new feature called [null coalescing operator](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op), and Laravel 5.7 only support PHP 7+. Also PHP 7.1.3 is required (see composer.json). So, the problem here is that your PHP version does not meet the requirements of the project.
